export const products = [
    {
       "id":"1",
       "name":"Galaxy S22 Ultra",
       "price":"1199",
       "stock":"5",
       "category":"galaxyS",
       "memory":"256",
       "image": "https://images.samsung.com/is/image/samsung/p6pim/levant/2202/gallery/levant-galaxy-s22-ultra-s908-413037-sm-s908ezkgmea-530970280",
       "review1": '"Las fotos en modo retrato más increíbles vi en un teléfono inteligente hasta ahora”.',
       "reviewer1": 'The Verge',
       "review2": '"El mejor de su clase, con una camara incomparable".',
       "reviewer2": 'Digital Trends',
       "procesador":"Octa-core(2.99GHz, 2.4GHz, 1.7GHz.)",
       "ram": "12",
       "camara": "Cuádruple, 108MP+10MP +10MP+12MP",
       "bateria":"5000 mAh",
       "os":"Android 12",
       "peso":"228"

   },
   {
       "id":"2",
       "name":"Galaxy S22 Plus",
       "price":"999",
       "stock":"4",
       "category":"galaxyS",
       "memory":"256",
       "image": "https://images.samsung.com/is/image/samsung/p6pim/es/2202/gallery/es-galaxy-s22-plus-s906-sm-s906bzkgeub-530863359?$650_519_PNG$",
       "review1": '"Tiene una pantalla increíble, rendimiento sólido y batería de larga duración".',
       "reviewer1": 'Gizmodo',
       "review2": '"Se siente como un dispositivo casi perfecto para quienes prefieren smartphones más pequeños”.',
       "reviewer2": 'CNET',
       "procesador":"Octa-core(2.99GHz, 2.4GHz, 1.7GHz.)",
       "ram": "8",
       "camara": "50.0 MP + 10.0 MP + 12.0 MP",
       "bateria":"5000 mAh",
       "os":"Android 12",
       "peso":"167"
       
   },
   {
       "id":"3",
       "name":"Galaxy S21 FE",
       "price":"799",
       "stock":"7",
       "category":"galaxyS",
       "memory":"128",
       "image": "https://image-us.samsung.com/SamsungUS/home/mobile/phones/pdp/galaxy-s21-fe-5g/gallery/SM-G990U-graphite-1.png",
       "review1": '"El mejor dentro de su categoria de calidad y precio".',
       "reviewer1": 'Gizmodo',
       "review2": '"Un precio bajo para la experiencia de usuario que ofrece".',
       "reviewer2": 'CNET',
       "procesador":"Snapdragon 888",
       "ram": "6",
       "camara": "Triple, 12 MP + 12 MP + 8 MP.",
       "bateria":"4.500 mAh",
       "os":"Android 12",
       "peso":"177"
   },
   {
       "id":"4",
       "name":"Galaxy Z Fold4",
       "price":"1499",
       "stock":"7",
       "category":"galaxyZ",
       "memory":"512",
       "image": "https://tienda.personal.com.ar/images/Galaxy_Z_Fold4_GG_Back_Open_min_b34cf2f5df.png",
       "review1": '"El Z Fold4 sigue siendo inigualable en términos de productividad y multitareas".',
       "reviewer1": 'Forbes',
       "review2": '"Los dispositivos plegables están a punto de ser MUCHO MÁS que dispositivos".',
       "reviewer2": 'TechRadar',
       "procesador": "Qualcomm Snapdragon 8+ Gen 1",
       "ram": "12",
       "camara": "Triple, 50 MP + 12 MP + 10 MP.",
       "bateria":"4.400 mAh",
       "os":"Android 12",
       "peso":"239 "
   },
   {
       "id":"5",
       "name":"Galaxy Z Flip4",
       "price":"999",
       "stock":"4",
       "category":"galaxyZ",
       "memory":"256",
       "image": "https://www.mgmstore.com.ar/1356-large_default/Samsung-Galaxy-Z-Flip-4-5G-256GB.jpg",
       "review1": '"Los dispositivos plegables están a punto de ser MUCHO MÁS que dispositivos".',
       "reviewer1": 'TechRadar',
       "review2": '"...el Galaxy Z Flip4 es el mejor de su clase".',
       "reviewer2": 'Digital Trends',
       "procesador":"Snapdragon 8+ Gen 1.",
       "ram": "12",
       "camara": "Principal: sensor de 12 megapíxeles con fotodiodos de 1,8 μm. Ultragran angular: sensor de 12 megapíxeles con fotodiodos de 1,12 μm",
       "bateria":"3700 mAh",
       "os":"Android 12",
       "peso":"187"
   },
   {
       "id":"6",
       "name":"Galaxy Z Fold3 5G",
       "price":"1299",
       "stock":"2",
       "category":"galaxyZ",
       "memory":"256",
       "image": "https://images.samsung.com/is/image/samsung/p6pim/ar/sm-f926bzkaaro/gallery/ar-galaxy-z-fold3-f926-5g-397281-sm-f926bzkaaro-thumb-496216258?imwidth=720",
       "review1": '"Los dispositivos plegables están a punto de ser MUCHO MÁS que dispositivos".',
       "reviewer1": 'TechRadar',
       "review2": '"...el Galaxy Z Flip4 es el mejor de su clase".',
       "reviewer2": 'Digital Trends',
       "procesador":"Octa-core(2.84GHz, 2.4GHz, 1.8GHz.)",
       "ram": "12",
       "camara": "Triple, 12MP + 12MP +12 MP",
       "bateria":"3700 mAh",
       "os":"Android 12",
       "peso":"271"
   },
   {
       "id":"7",
       "name":"Galaxy A52",
       "price":"459",
       "stock":"8",
       "category":"galaxyA",
       "memory":"128",
       "image": "https://wikimovel.com/images/thumb/e/ed/Samsung-Galaxy-A52.png/300px-Samsung-Galaxy-A52.png",
       "review1": '"De los mejores dispositivos gama media en su año".',
       "reviewer1": 'TechRadar',
       "review2": '"Sin duda el mejor de su segmento".',
       "reviewer2": 'Digital Trends',
       "procesador": "Qualcomm SM7125 Octa Core (2 x 2.3GHz + 6 x 1.8GHz)",
       "ram": "6",
       "camara": "Cuadruple, 64MP + 12MP + 5MP + 5MP",
       "bateria":"4900 mAh",
       "os":"Android 11",
       "peso":"189"
   },
   {
       "id":"8",
       "name":"Galaxy A53 5G",
       "price":"599",
       "stock":"7",
       "category":"galaxyA",
       "memory":"128",
       "image": "https://images.samsung.com/is/image/samsung/p6pim/ar/2202/gallery/ar-galaxy-a53-5g-a536-sm-a536ezoaaro-531544702?$650_519_PNG$",
       "review1": '"Un diseño simple, creado para destacar".',
       "reviewer1": 'Gizmodo',
       "review2": '"Asombrosa pantalla AMOLED, para el segmento de precio en el que se encuentra".',
       "reviewer2": 'Digital Trends',
       "procesador": "Octa Core 2.4GHz,2GHz",
       "ram": "6",
       "camara": "Cuadruple, 64MP + 12MP + 5MP + 5MP",
       "bateria":"5000 mAh",
       "os":"Android 11",
       "peso":"189"
   },
   {
       "id":"9",
       "name":"Galaxy A72",
       "price":"699",
       "stock":"4",
       "category":"galaxyA",
       "memory":"128",
       "image": "https://images.samsung.com/is/image/samsung/p6pim/ar/sm-a725mzbaaro/gallery/ar-galaxy-a72-a725-377975-sm-a725mzbaaro-409830543?$650_519_PNG$",
       "review1": '"Una asombrosa pantalla con un desplazamiento extrafluido".',
       "reviewer1": 'Gizmodo',
       "review2": '"Un dispositivo movil con una versatilidad unica en su segmento".',
       "reviewer2": 'TechRadar',
       "procesador": "Octa-Core (2 x 2,3 GHz + 6 x 1,8 GHz)",
       "ram": "8",
       "camara": "Cuadruple, 64MP + 12MP + 5MP + 8MP",
       "bateria":"5000 mAh",
       "os":"Android 11",
       "peso":"198"
   },
   {
       "id":"10",
       "name":"Galaxy A52s 5G",
       "price":"549",
       "stock":"3",
       "category":"galaxyA",
       "memory":"128",
       "image": "https://storage.comprasmartphone.com/smartphones/samsung-galaxy-a52s-5g.png",
       "review1": '"Un dispositivo movil con una versatilidad unica en su segmento".',
       "reviewer1": 'TechRadar',
       "review2": '"Camara nitida y estable".',
       "reviewer2": 'Gizmodo',
       "procesador": "Snapdragon 750G 5G",
       "ram": "6",
       "camara": "Cuadruple, 64MP + 12MP + 5MP + 8MP",
       "bateria":"5000 mAh",
       "os":"Android 11",
       "peso":"198"
   },
   {
       "id":"",
       "name":"",
       "price":"",
       "stock":"",
       "category":"",
       "memory":"",
       "image": ""
   }
]

